### ISSUE TITLE
show the day?

### ISSUE THREAD

**Issue by huanBird** [phucgaoxam/slide_countdown_clock#2]
Hello, if your plugin time is more than 24 hours. Can show the day (day:hour:Minutes : seconds)?

**Comment by phucgaoxam** [comment]
sure please wait for the next update

**Comment by huanBird** [comment]
thinkyou ?

**Comment by phucgaoxam** [comment]
hi @huanBird 
I have just released version 1.0.3, please try it.
If you want to show the days, please set **shouldShowDay** parameter to **true**

**Comment by huanBird** [comment]
ok
